### ISSUE TITLE
Broken Page

### ISSUE THREAD

**Issue by roshan1885** [mahtab2003/Xera#50]
Found a broken Page
Url: /a/ssl
Error: CSS doesn't loads.
Image:
![190137202-bba88bc7-1dc3-4002-942e-a51abc6097ec](https://user-images.githubusercontent.com/81822450/190423107-f84972fb-9140-443a-aa61-fbe81e2ead28.png)

**Comment by mahtab2003** [comment]
ok let me check

**Comment by AgentDeath253** [comment]
@OnionDev1885  are you using custom email templates

**Comment by roshan1885** [comment]
> @OnionDev1885 are you using custom email templates

Yes. But I have plain templates now.
M planning for css ones.

**Comment by 4yx** [comment]
Nevermind, scratch that. I had the chance to visit a newer Xera installation and it appears the issue exists anyway.
No clue as to what's causing it, for some reason the header and footer that are supposed to be included in these pages aren't included in the SSL one.

**Comment by AgentDeath253** [comment]
well it looks like it started after the crypto loot update

**Comment by mahtab2003** [comment]
maybe

**Comment by roshan1885** [comment]
I have noticed, that its fine till there are no SSL requests done (pending, processing, completed, any)
As soon as someone issues an SSL (no matter its processed or not), the admin SSL page gives error (CSS doesn't loads)

**Comment by Ronogamer7771** [comment]
Hi! 
I uploaded xera client area for the first time on one host but I have setup xera multiple times and I have never gotten this error

I make admin account but dashboard says this

An Error Was Encountered
Unable to load the requested file: page/includes/admin/header.php

**Comment by mahtab2003** [comment]
hm m

**Comment by 4yx** [comment]
After some extensive debugging, I was able to find out what's causing the issue.
In ``template\default\page\admin\ssl.php``, lines 77 and 81 contain the expression ``$this->ssl->list_count()``, which breaks the code and prevents the page from loading correctly. Removing the lines that contain the expression or replacing it with a numeric value (for example ``1``) allows the page to load correctly again.

I'm assuming the issue exists in the function ``list_count`` in ``app\models\Gogetssl.php``, but I have no clue as to how it would be fixed. Someone experienced in PHP could take a look and see if they can identify the issue.

**Comment by greenreader9** [comment]
My guess is that the function is returning "FALSE" or _NULL_, Probably because there is no fallback. I will take a look tomorrow if I remember, no use looking at it on my phone.

**Comment by 4yx** [comment]
I was able to find out what's causing it and will make a PR along with some other fixes soon.

> My guess is that the function is returning "FALSE" or _NULL_, Probably because there is no fallback. I will take a look tomorrow if I remember, no use looking at it on my phone.

I thought to try and test this out after you mentioned it, but as my tests produced nothing, I kept checking. Then I realized that the page was showing "Showing 1 to 1 of Array entries"; realizing that the code was incorrectly returning an Array instead of counting the elements in it as intended.
I'm unsure if the way I fixed it is correct, so if you could review it that would be great.

**Comment by roshan1885** [comment]
> After some extensive debugging, I was able to find out what's causing the issue. In `template\default\page\admin\ssl.php`, lines 77 and 81 contain the expression `$this->ssl->list_count()`, which breaks the code and prevents the page from loading correctly. Removing the lines that contain the expression or replacing it with a numeric value (for example `1`) allows the page to load correctly again.
> 
> I'm assuming the issue exists in the function `list_count` in `app\models\Gogetssl.php`, but I have no clue as to how it would be fixed. Someone experienced in PHP could take a look and see if they can identify the issue.

so bro, can u say me what changes shall i make here?
![image](https://user-images.githubusercontent.com/81822450/193069898-dbdf5f22-59c5-4489-8bdd-30c9b9cac3d1.png)
I don't know php, so can u provide me the preview of the fixed code?
[Yes I changed the whole file of admin/ssl.php from the current one. And still the issue isn't solved. I also tried clearing cookies]

**Comment by 4yx** [comment]
> so bro, can u say me what changes shall i make here? ![image](https://user-images.githubusercontent.com/81822450/193069898-dbdf5f22-59c5-4489-8bdd-30c9b9cac3d1.png) I don't know php, so can u provide me the preview of the fixed code? [Yes I changed the whole file of admin/ssl.php from the current one. And still the issue isn't solved. I also tried clearing cookies]

I assume you also copied the new ``app\models\Gogetssl.php`` over, and cleared the cache, if you did not do those please do them. The issue was in ``Gogetssl.php``, but it is resolved in my local installation.
If you've also done those and it still does not work please let me know.

**Comment by roshan1885** [comment]
Thank You so much for your contribution! Issue was fixed :)

**Comment by 4yx** [comment]
> Thank You so much for your contribution! Issue was fixed :)

You're very welcome! I'm glad to hear it :)
